### ISSUE TITLE
existingConfigMapName is not working for ProxyFleet

### ISSUE THREAD

**Issue by stevefan1999-personal** [jeremylvln/Shulker#447] opened 2024-03-07 17:32 UTC
### What happened?

Setting an existingConfigMapName for ProxyFleet is not working. It will always set to be the default template. Modifying the default template will always revert back to the default anyway.

I need to set force-key-authentication to false in velocity-config.toml because I'm not using Local external traffic load balancer mode, because I'm self hosting a Kubernetes cluster running with Cilium. The default load balancer coming with Cilium does not have good support for Local mode because it is based on SNAT (despite there is a DSR mode that theoretically supports direct source IP forward with GENEVE, I failed to make it work correctly and I'm stuck with SNAT).

### Version

0.7.0

### Kubernetes Version

1.29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment] 2024-03-11 12:55
Hi @stevefan1999-personal!

Thanks a lot for reporting the issue. The configuration field was present but was not used at all for the proxies. I've opened a PR to fix it. Let me know once merged & built if it fixes your issue (use the `next` image tag for the operator) :)

**Comment by TehNeon** [comment] 2024-03-25 01:59
I may have attempted to utilize this feature incorrectly. But it sounds like it's meant to allow for the overriding of the config map that provides the proxy config (velocity-config.toml as defined in the Shulker provided configmap). But in actual usage, it appears that it wants the`init-fs.sh` file to be defined in the config map, also likely other files like the probe-readiness.sh. I'm not sure if this is the intended behaviour to allow for the overriding of the `init-fs.sh`.

**Comment by jeremylvln** [comment] 2024-03-25 09:46
It's currently a total overwrite you are write. I can't cherry-pick parts of the ConfigMap, I really want to keep this on the Kubernetes-level by changing the name of the ConfigMap. However I understand it could be an issue. Maybe it would be useful to split the ConfigMap to isolate the bootstrapping scripts from the config files themselves.

**Closed** 2024-03-25 10:55 UTC
Labels: type:bug :bug:

**Comment by stevefan1999-personal** [comment] 2024-04-21 06:18
Not working for MinecraftServerFleet either

https://github.com/jeremylvln/Shulker/blob/5937788352edeeee94f77a72f7583de43e486b37/packages/shulker-operator/src/reconcilers/minecraft_server_fleet/fleet.rs#L59-L61

@jeremylvln

**Comment by jeremylvln** [comment] 2024-04-22 08:13
Jeez. Nice catch. I totally forgot about the fleet. Will fix shortly.

Thanks!
